install.packages("caret")
install.packages("C50")
data("iris")
library(caret)
library(C50)
inTraininglocal<-createDataPartition(iris$Species,p=0.75,list=F)
training<-iris[inTraininglocal,]
testing<-iris[-inTraininglocal,]
model<-C5.0(training$Species~.,data=training)
summary(model)
pred<-predict.C5.0(model,testing[,-5])
a<-table(testing$Species,pred)
sum(diag(a))/sum(a)
