library(plyr)
x<-runif(50)
y<-runif(50)
data<-cbind(x,y)
plot(data)
km<-kmeans(data,4)
install.packages("animation")
library(animation)
windows()
km<-kmeans.ani(data,4)
wss<-c()
for(i in 2:15)wss[i]<-sum(kmeans(data,centers=i)$withinss)
plot(1:15,wss,type="b",xlab="No of clusters",ylab="Avg distance")